### ISSUE TITLE
Добавление новых состояний операции

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#163]
В некоторых случаях процессы запуска и остановки операции являются длительными процессами, которые нельзя прерывать, поэтому могут понадобиться состояния Starting и Stopping, из которых мы переходим в Run и Stop соответственно. При этом при переходе из паузы в выполнение Starting может быть нужен не всегда.

**Comment by AlexandraNovik** [comment]
Добавление состояний не решает всех вопросов, связанных с дополнительными проверками (check_on_start и т.д.).

**Comment by idzm** [comment]
@pupenasan - нужно ваше мнение.

**Comment by pupenasan** [comment]
Мы используем расширенную модель состояния. 
![зображення](https://user-images.githubusercontent.com/25325920/102891932-c1e0fd80-4467-11eb-8247-31f406f37b4b.png)
Из паузы выход без переходного процесса. Но есть еще Holding, там переходное состояние есть. Вобщем по диграмме всё видно.

**Comment by idzm** [comment]
То есть, согласно данной диаграмме (и стандарту), должно быть такое поведение. Если что-то не удаётся так реализовать - надо смотреть реализацию - возможно, есть ошибки в выделении агрегатов, шагов и т.п.

**Comment by pupenasan** [comment]
> 
> 
> То есть, согласно данной диаграмме (и стандарту), должно быть такое поведение. Если не удаётся так сделать - надо смотреть реализацию - возможно, есть ошибки в выделении агрегатов, шагов и т.п.

нет, это просто один из примеров. Стандарт ничего не ограничивает в этом плане.
