### ISSUE TITLE
Импульсное включение устройств

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#172]
Периодически отдельные устройства клапана, моторы, сигналы нужно включать на определенное время, а потом сбрасывать. Не всегда их удается разместить в шагах, которые работают по времени, например, одновременно нужно подать сигнал и включить мотор, но на разное время. Для реализации этого сейчас приходится создавать флаги, засекать время, если таких устройств много, то становится достаточно сложно за этим следить. 
Было бы удобно в устройствах задать в параметр, например, IMPULSE_TIME. Если оно не отрицательное (по умолчанию), то после вызова функции включения, через время, заданное параметром, устройство отключится. Параметр тогда нужно иметь возможность задать из программы аналогично производительности мотора.

**Comment by idzm** [comment]
@KUZMA-1989, @AndreiSavushkin - что скажет по данной функциональности?

**Comment by AndreiSavushkin** [comment]
Подходит под нашу реализацию флипования клапанов. Добавить возможность для каждой группы задавать свои таймеры работы (время включения и интервал + не только клапаны типа микспруф) и будет работать как описано выше. Если параметры для группы не заданы, то использовать стандартные системные параметры.

**Comment by idzm** [comment]
@AlexandraNovik - что скажешь на комментарий Андрея?

**Comment by AlexandraNovik** [comment]
Звучит хорошо, если нужно использовать постоянное включение-выключение в рамках одного шага, насколько я понимаю. Но еще может быть необходимость сделать это один раз при попадании в шаг или по каким-то условиям в коде (например, при увеличении каких-либо счетчиков)

**Comment by idzm** [comment]
Предлагается использовать для этой цели шаги. Шаги могут одновременно выполняться и в них можно группировать требуемые устройства.
