### ISSUE TITLE
Работа с множественными шагами операции

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#174]
- [x] В настоящее время есть возможность включения нескольких шагов одновременно, но при этом старая функция получения номера включённого шага `active_step()` возвращает 0, а возможности проверить включён ли один из шагов нет. Функция `is_active_extra_step` не доступна из **Lua**. Было бы проще, чтобы мы её также получали `m_mngr[ mode ]:is_active_extra_step (int n)` от текущего состояния операции, без промежуточного этапа:
```
local run_state = oper[ operation.PAUSE ]
run_state:is_active_extra_step (int n)
```
- [x] Для каждой операции в БК создаются теги в виде `OBJ.STEPSN[ M ]`, где N - номер операции, M - номер шага. сейчас максимальное количество этих тегов определяется количеством тегов в состоянии Выполнение. Для работы с шагами не должно быть разницы , в каком состоянии мы находимся. Количество тегов должно определяться тогда максимальным количество шагов в любом из состояний или передаваться одним  тегом (например, `EXTRA_STEPS[ N ]`, где N - номер операции) как передаётся ST объекта со включёнными операциями (это может значительно сократить количество тегов и в мониторе их не придётся перебирать по одному).

**Comment by idzm** [comment]
Вот сборка для тестирования - [lua_vscode.zip](https://github.com/savushkin-r-d/ptusa_main/files/5813998/lua_vscode.zip).
