### ISSUE TITLE
Модернизация и исправления ошибок устройства M_ATV

### ISSUE THREAD

**Issue by AndreiSavushkin** [savushkin-r-d/ptusa_main#205]
С устройствами M_ATV и текущей реализации ошибки устройства имеются проблемы:
- [x] С недавних пор, судя по всему что-то поменялось в устройствах M_ATV (ЧП по модбас). В частности - с обратной связью. Например, если открывается люк, то возникает авария устройства «Мешалка» и все операции становятся в Паузу, хотя мешалка даже не должна была быть включена. Да, при открытии люка срабатывает STO, но ведь при неработающей мешалке это вовсе не авария устройства. Да, ЧП в таком случае не готов, это другое состояние. Но это вовсе не авария. Вот если нужно включить мешалку и ЧП находится в STO, то вот это авария. Это конкретно мешает вести технологический процесс. Исправлено в https://github.com/savushkin-r-d/ptusa_main/pull/289.
- [x] Также есть замечания по открытию люка при включенной мешалке (через узел перемешивания). Программное обеспечение при открытии люка учитывает сигнал с датчика люка выключает мешалку (узел перемешивания в паузу) и при обратном закрытии мешалка включается автоматически. При открытии люка срабатывает, как уже отмечалось, система безопасного останова STO. В итоге в нашей системе возникает авария устройства мешалки раньше, чем ПО выключает мешалку. По итогу мы имеем аварию устройства и операцию в Паузе (даже при установке фильтра дребезга датчика люка на 0). А должно быть так – работает мешалка, открываем люк, мешалка выключается (узел в пауза), закрываем люк – мешалка включается (узел в выполнение). При управлении через входы / выходы это работало со следующими настройками – обратная связь настроена на «ПЧ работа» с задержкой выключения 0,5 с. Исправлено в https://github.com/savushkin-r-d/ptusa_main/pull/289.
- [ ] Основным показателем работы какого-либо электропривода является потребляемый электродвигателем ток, поэтому необходимо сделать, чтобы у устройства M_ATV (Modbus) передавалось значение тока, потребляемого электродвигателем (настройка в ЧП – Ток двигателя). Причем это значение должно быть не только для отображения и архивирования в SCADA-системе, но также и доступно в контроллере для выполнения каких-либо действий (регулирование, блокировки, переходы к другим операциям/шагам и т.д.). Исправлено в https://github.com/savushkin-r-d/ptusa_main/pull/405.
- [x] Потеря связи с ЧП является просто аварией устройства. Ее никак нельзя сравнивать с отсутствием связи с узлом, контроллером. Частотный преобразователь может быть выключен для замены, для ремонта, для демонтажа и это никак не должно сказываться на выдаче сообщений от контроллера. Исправлено в #337.
- [ ] Есть вопросы и по работе на частоте больше 50 Гц. При управлении устройством M_ATV следует задавать в свойство «аналоговое значение» больше ста – вручную это возможно сделать. Но при регулировании ПИД-регулятором при текущей реализации это сделать невозможно. Да и отображение и задание 120 % как-то не очень красиво выглядит. При настройке через дискретные и аналоговые сигналы на ЧП настраивалась максимальная частота двигателя 60 Гц (TFR), максимальное задание частоты аналогового сигнала – 60 Гц, и при 20 мА аналогового выхода двигатель работал на частоте 60 Гц. Возможно, следует для устройства ввести еще одно свойство fmax, в котором будет задаваться максимальная частота электродвигателя в Гц. А уже само устройство M_ATV будет масштабировать выходной сигнал ПИД-регулятора или любой другой в диапазоне 0-100 % в требуемую частоту электродвигателя и включать уже с этой частотой (похоже, что сейчас выходной сигнал делится на 2 и полученное значение посылается в ЧП в качестве задания в Гц). В качестве fmax лучше взять непосредственно настройку частотного преобразователя TFR. Можно и как дополнительный параметр устройства M_ATV, но в таком случае может быть несоответствие заданной частоты с реальной. Исправлено в https://github.com/savushkin-r-d/ptusa_main/pull/405.

**Comment by KUZMA-1989** [comment]
@rartem В последнем пункте считывается параметр HSP (High speed) для задания частоты насосу при 100% ?

**Comment by rartem** [comment]
> @rartem В последнем пункте считывается параметр HSP (High speed) для задания частоты насосу при 100% ?

Используется параметр мотора:
TFR | Max. output   frequency.
