### ISSUE TITLE
Переход к новому шагу после включения/выключения устройств

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#211]
Нужна возможность для шага задать список устройств для проверки включенного состояния и выключенного состояния и получить по этим полям итоговые результаты.
Контроль включения: DEV1, DEV2, ... DEVn.
Контроль выключения: DEV1, DEV2, ... DEVm.
Можно было бы задать список устройств и получить к нему доступ из Lua, чтобы перебрать самим (проверить включены или выключены).
Но устройства могут быть разного типа: датчики и сигналы, состояние которых мы можем проверить get_state(), клапаны (цилиндры), обратные связи которых проверяем через is_closed() и is_opened(). Но есть еще моторы, как проверить, что они уже включены? И мы не получаем тип устройства, чтобы знать, как их проверить.
Проще было бы получить общий ответ по каждому из полей step_devs:is_on() - true|false, step_devs:is_off().
Можно было бы задать устройства в оборудовании объекта, но некоторые объекты работают просто как переключение шагов, количество которых может быть вариативно из-за механического исполнения (зависит от места, продукта, объекта, могут быть разными по назначению, но одинаковыми по принципу работы), поэтому задать их в оборудовании некорректно, тем более что эти поля придется задавать по количеству шагов (уже сейчас в некоторых объектах так до 14 шагов).

**Comment by AlexandraNovik** [comment]
Как обещали пример функциональности по шагам, которую нужно сделать. Накопитель, который реализует забор продукта.

Шаг 1. "Ожидание запроса работы накопителя".
Если появился сигнал Запрос работы, переходим к шагу 2.

Шаг 2. "Поднятие цилиндра V2"
Включить: V2.
Если цилиндр поднят, пришла обратная связь, что он открыт, переход к шагу 3.

Шаг 3. "Выдвинуть V1"
Включить: V1.
Если цилиндр выдвинут, пришла обратная связь, что он открыт, переход к шагу 4.

Шаг 4. "Опустить V2"
Выключить: V2
Если цилиндр опущен, пришла обратная связь, что он закрыт, переход к шагу 5.

Шаг 5. "Ожидание продукта"
Если сработал датчик наличия продукта, переход к шагу 6.

Шаг 6. "Задвинуть V1".
Выключить: V1
Если цилиндр задвинут, пришла обратная связь, что он закрыт, переход к шагу 1.

**Comment by idzm** [comment]
Отлично, спасибо. Ещё нужен пример Lua-кода реализации для текущей функциональности и такой же пример для при появлении будущей (которая предлагается в данном запросе) функциональности.

**Comment by AlexandraNovik** [comment]
Примерное описание кода в функции function basic_step_switch_node:eval_steps( mode ) файл step_switch.lua в robotic-sys
Там пример кода для перехода к следующему шагу, если шаги последовательные.

**Comment by idzm** [comment]
А можно, пожалуйста, здесь данный фрагмент привести - смотреть буду не я один, это ускорит процесс.

**Comment by AlexandraNovik** [comment]
`--Получение списков устройств для проверки включения/выключения
        local checking_on = m_mngr[ mode ]:step_checking_on( step )
        local checking_off = m_mngr[ mode ]:step_checking_off( step )

        --Проверка всех устройств из списков
        local is_on = false
        local is_off = false

        --Если список устройств для включения не задан, то считаем, что все включено
        if #checking_on ~= 0 then
            is_on = true
            for i = 1,  #checking_on do
                local dev = checking_on[i]
                --Проверка устройства на включенное состояние
                if dev:is_on() == false then
                    is_on = false
                end
            end

        else
            is_on = true
        end

        --Если список устройств для выключения не задан, то считаем, что все выключено
        if #checking_off ~= 0 then
            is_off = true
            for i = 1,  #checking_off do
                local dev = checking_off[i]
                --Проверка устройства на включенное состояние
                if dev:is_off() == false then
                    is_off = false
                end
            end

        else
            is_off = true
        end

        --Если все устройства проверены и включены/выключены,
        --переходим к следующему шагу
        if is_on == true and is_off == true then
            if step < #self.steps then
                m_mngr[ mode ]:to_step( step + 1 )
            else
                m_mngr[ mode ]:to_step( 1 )
            end
        end`

**Comment by idzm** [comment]
То есть, предполагается расширить базовые способы описания перехода к следующему шагу - сейчас имеется механизм перехода по истечению заданного времени (параметр). Предлагается добавить группу включаемых/выключаемых устройств - когда данные устройства включились/выключились, то мы переходим к следующему шагу.
@AndreiSavushkin, @KUZMA-1989 - нужно ваше мнение по данному вопросу.
