### ISSUE TITLE
Одинаковый механизм работы шагов в различных состояниях

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#221]
На данный момент в состоянии операции **"Выполнение"** всегда включается шаг **№1**, даже если список шагов для данного состояния не задан.
Для состояний **"Пауза"** и **"Стоп"** по умолчанию шаги вообще не предусмотрены (в **EPLANner**-е нет полей устройств для заполнения), даже если задан список шагов, функция active_step() возвращает 0. Чтобы вернуть первый шаг, нужно принудительно внести его в список шагов в **EPLANner**-е для данных состояний и при переходе в них принудительно его включить в функции **on_pause** или **on_stop**.
Получается неодинаковая схема работы для разных состояний.

**Comment by idzm** [comment]
> На данный момент в состоянии операции "Выполнение" всегда включается шаг №1, даже если список шагов для данного состояния не задан.

@AlexandraNovik - не совсем понятно. Если нет списка шагов, то как может включиться шаг №1?

**Comment by idzm** [comment]
@AndreiSavushkin, @KUZMA-1989  - нужно ваше мнение по данному вопросу.

**Comment by AlexandraNovik** [comment]
В состоянии выполнение, если список шагов не задан active_step() возвращает единицу. и в мониторе тег номер включенного шага присылает 1

**Comment by idzm** [comment]
> 
> 
> В состоянии выполнение, если список шагов не задан active_step() возвращает единицу. и в мониторе тег номер включенного шага присылает 1

Для операции, которая находится в  состоянии выполнение, если список шагов не задан, то функция **active_step()**  возвращает единицу. Также в мониторе в тег номера включённого шага приходит значение, равное единице. Вот пример кода для тестирования:

```lua
function tank:user_evaluate()
    if self:get_mode( self.operations.FILL ) == 1 then
        local m_mngr = self:get_modes_manager()
        local oper   = m_mngr[ self.operations.FILL ]
        local a_step = oper:active_step()
        print( a_step )                                                      --В консоли получаем 1.
    end
end
```

**Comment by idzm** [comment]
Нужен конкретный проект, где такое происходит - я тестировал и не обнаружил такого. У меня в данной ситуации возвращается ноль - корректное значение.
