### ISSUE TITLE
Доработка аварийных значений для устройств IO-Link

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/ptusa_main#222]
Должна быть возможность задания (через параметр) аварийного значения для устройств IO-Link. Связанная задача **EPLANner** - https://github.com/savushkin-r-d/EasyEPLANner/issues/332.

**Comment by KUZMA-1989** [comment]
@idzm Добавить выдачу сообщений об авариях датчиков IOLink, когда пропадает связь с датчиком. Следующим этапом будет постановка в паузу (надо будет обсудить).

**Comment by idzm** [comment]
Постановка операции в паузу по аварии концентратомера уже реализована в системных Lua-скриптах. Постановка операции в паузу при аварии определённых датчиков будет оформлена в виде отдельного запроса.
