### ISSUE TITLE
Кратковременное пропадание входящих сигналов при переходе операции в состояние "Пауза" 

### ISSUE THREAD

**Issue by FedoseevYuri** [savushkin-r-d/ptusa_main#277]
**На проекте «BN1-Танки-пастеризованной-воды» была выявлена следующая особенность работы операций при переходе в состояние «Пауза».**

_Логика работы при выдаче пастеризованной воды была реализована следующим образом:_
1)От Bertsch приходит сигнал «Готов к производству», когда линия собрана и отсутствуют ошибки устройств. Если во время производства 
2) По сигналу «Запрос подачи пастеризованной воды» включаем насос подачи и подаем сигнал «Подача пастеризованной воды», отсчитываем объем линии, после чего отправляем сигнал «Пастеризованная вода у цели» и начинаем транслировать Bertsch значение текущего количества поданной пастеризованной воды через аналоговый сигнал. Когда сигнал «Запрос подачи пастеризованной воды» снимается Bertsch, в проекте останавливается работа насоса и обнуляется значение поданного количества пастеризованной воды. Когда сигнал вновь появляется насос включается и отсчет поданного количества воды начинается с нуля.
 
_Проблема:_
При пропадании сигнала «Готов к производству», операция «Выдача» по линии PW2 становится в паузу, при этом, на долю секунды, происходит пропадание сигнала «Запрос пастеризованной воды», что приводит к обнулению значения поданной пастеризованной воды на Bertsch. Текущее количество поданной воды используется Bertsch для корректного наполнения коагуляторов.
После проверки кратковременного пропадания сигнала с нашей стороны и со стороны Bertsch, было выявлено, что причиной является переход операции «Выдача» в паузу.

_Временное решение для работы:_
Поскольку с использованием состояния «Пауза» возникли сложности, выдача на Bertsch была реализована через использование логического И для работы насоса подачи воды по сигналам «Запрос подачи пастеризованной воды» и «Готов к производству». Но при неисправности устройств линии со стороны нашей проекта, операция будет переведена в паузу и значение текущего количества поданной воды будет  обнулено.

![Сигналы](https://user-images.githubusercontent.com/28864957/123419074-7ba95a00-d5c2-11eb-9200-d89c6bb9cc5c.png)
Рисунок 1 - Сигналы для работы с линией пастеризации Bertsch

![Тренды сигналов](https://user-images.githubusercontent.com/28864957/123419079-7c41f080-d5c2-11eb-9e09-27860e5f3ec1.png)
Рисунок 2- Тренды обмена сигналов

**Comment by FedoseevYuri** [comment]
@KUZMA-1989, @painterlv, @AlexandrBehunkov - прошу принять участие в рассмотрении данной момента.

**Comment by idzm** [comment]
@FedoseevYuri - «Запрос пастеризованной воды» - это **PW2DO1**?

**Comment by FedoseevYuri** [comment]
@idzm - Да.

**Comment by AlexandraNovik** [comment]
У нас в проектах используется объект, в работе которого есть шаги в состояниях "Выполнение" и "Пауза". В шагах каждого из состояний есть управление состоянием цилиндра (Вкл/Выкл), которое прописывается в еплане. При переходе из Выполнения в Паузу необходимо сохранить состояние устройства и перейти в нужный шаг Паузы, в котором состояние устройства соответствует его состоянию в Выполнении. При этом дребезга не наблюдалось. 
Если цилиндр был включен, то он сохраняет свое включенное состояние  и в Паузе. Если что время включения/выключения цилиндра 100 мсек, а цикла программы 25-30 мсек, было бы заметно, что он дергается. В программе принт для проверки тоже не находит выключения устройства.

**Comment by idzm** [comment]
Проблемы нет - при переходе в паузу всё корректно включается. Если вопрос остался, то надо в рамках конкретного проекта задавать вопрос и искать решение.
