### ISSUE TITLE
Проблемы на 555 операции мойки

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa_main#332]
В некоторых ситуациях на мойке происходит следущая ситуация: зависает контроллер на 555 операции 
![image](https://user-images.githubusercontent.com/58733814/142419775-a051b773-4d71-4c8e-b086-666d13e1babd.png)
Помогает физическая перезагрузка. При подключении к контроллеру бывают ситуации, когда можно подключиться, а когда нет.
В случае подключения к контроллеру нельзя перезагрузить проект командами: 
```
sudo /etc/init.d/plcnext restart;
sudo reboot.
```
При подключении при помощи PLCnext Engineer получаю сообщение, что не могу подключиться к контроллеру.
В браузере нельзя подключиться, т.к. он постоянно загружает данную страницу.
![image](https://user-images.githubusercontent.com/58733814/142420414-a2261fb5-e65f-4f97-8faa-b47f82ba61ae.png)

**Comment by idzm** [comment]
Закрыто за длительной неактивностью.
