### ISSUE TITLE
Работа устройства CAM

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#374]
- [x] В результате проверки устройства на реальном оборудовании нашлась ошибка, перепутаны каналы готовности и результата обработки:
Если мы задаем подтип **CAM_DO1_DI2**, то DI готовности и результата приходят в обратные теги.
Если задаем подтип **CAM_DO1_DI1** (устройство без сигнала готовности, только с результирующим сигналом), то когда сигнал приходит на нужную клему результата, в свойстве Result устройства CAM все равно 0.
- [x] Также для камеры нет возможности в программе получить состояние готовности (функция get_ready()). Функция get_state() возвращает, то что мы установили в set_state(), а именно триггер.

> Для получения состояния готовности камеры добавлена функция `is_ready()`.

- [ ] Авария в устройстве подтипа **CAM_DO1_DI2** должна возникать, если сигнал DI о готовности камеры пропал на заданное параметром P_READY_TIME время и выше. Сейчас в устройстве авария возникает в обратной ситуации, если сигнал о готовности возник на время выше **P_READY_TIME**, что не правильно. Или в ситуации, когда мы отправляем триггер DO, DI готовности отсутствует.

**Comment by idzm** [comment]
Для получения состояния готовности камеры добавлена функция `is_ready()`.
