### ISSUE TITLE
Единые функции проверки состояния устройств

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#375]
Сейчас для сигналов, датчиков есть возможность получить их состояние через функцию get_state(), для того, чтобы узнать включен или выключен клапан с обратными связями функции is_opened(), is_closed().
Если вместо клапана с ОС используется клапан без ОС или сигнал, то приходится перебирать функции и делать дополнительные флаги, какой тип устройства мы используем.
Нужна одна функция для всех устройств, позволяющая узнать включено/выключено устройство is_on(), is_off().

**Comment by idzm** [comment]
@AlexandraNovik - для всех устройств есть метод `is_active()`, можно его использовать для этих целей.

**Comment by idzm** [comment]
Закрыто за длительной неактивностью.
