### ISSUE TITLE
Добавление устройства - весы (RS-232)

### ISSUE THREAD

**Issue by FedoseevYuri** [savushkin-r-d/ptusa_main#379]
В систему нужно добавить новый подтип для устройства весы (WT_RS или WT_RS232 для понятности), передающее данные по интерфейсу RS-232. Такое устройство (весы ProMAS PM1H) будут использоваться в проекте BZ1-Затарка-сыра.

**Comment by AlexandraNovik** [comment]
В данном случае нам приходит строка в формате "+00.000kg". По идее нам нужна возможность получать строки любого содержания по RS-232.  А дальше уже работать с функция обработки строк, но они уже будут применяться в каждом индивидуальном случае
