### ISSUE TITLE
Добавить расходомер IO-LINK IFM SM6100

### ISSUE THREAD

**Issue by AndreiSavushkin** [savushkin-r-d/ptusa_main#396]
В связи с использованием расходомеров **IFM SM6100** на производстве (на МСА для внесения дезраствора), необходима реализация такого расходомера как устройства **IO-LINK**.
Следует реализовать следующие теги:
-поток в л/ч (с точностью до одного знака после запятой). Выбор единиц измерения л/ч обусловлен основной рабочей точкой 60-80 л/ч и для корректного протоколирования удобнее использовать данные единицы измерения.
-сумматор в мл (целочисленное). В существующих проектах уже используется эта размерность и является наиболее подходящей для наших применений.
-температура в гр. С (с точностью до одного знака после запятой).
При реализации других расходомеров **IO-LINK** возможны другие единицы измерения физических величин.

**Comment by idzm** [comment]
Документация здесь - https://www.ifm.com/download/files/ifm-SM6000-20161103-IODD11-en/$file/ifm-SM6000-20161103-IODD11-en.pdf.
![изображение](https://user-images.githubusercontent.com/23375200/163383533-adc8abef-82d2-4483-9ca3-8aff70aa8cab.png)
