### ISSUE TITLE
Возможность описания включаемых устройств с задержкой включения/отключения

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/ptusa_main#418]
Предлагается расширить функциональность действия "Включаемые устройства" - добавить параметр времени задержки включения устройства и параметр времени задержки отключения устройства. Включаемые запросы:
- [x] #411
- [x] #412

**Comment by AndreyNemenkov** [comment]
Две недели уже висит это предложение, а утверждалось, что за пару дней будет готово 🥇

**Comment by Serega-pixel** [comment]
@idzm  хотелось бы реализовать вторую часть запроса : "Задержка выключения устройств". Очень необходима для проекта
