### ISSUE TITLE
Некорректное включение шага при переходе из паузы в выполнение

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#423]
Тестировали проект укладка творожный. Мы используем пользовательские объекты, в которых есть шаги во всех состояниях (выполнение 7 шагов, пауза 5 шагов, остановка 4 шага - для проверки использовали конкретный объект, объект №8 Сбор продукта левый накопитель ).
Из любого шага выполнения он попадает в 1й шаг паузы, после чего корректно проходит по всем шагам и останавливается в 5м шаге (необходимо последовательно вернуть оборудование в исходное состояние). Если принудительно в коде функции on_statrt не прописать после выхода из паузы переход в 1 шаг выполнения, он начинает выполнение тоже с 5го шага.
Если в функции on_start указать принудительный переход в шаг 1, то согласно логу отрабатывает корректно, но судя по работе оборудования на доли секунды происходит заход в 5й шаг, который уже в луа мы не видим. На видео выход из паузы с 28 секунды.
Еще при попадании в паузу. У нас в первом шаге паузы происходит только проверка выключенного состояния устройства , если это так, то переходим во второй шаг. Если это устройство на момент попадания в паузу уже было выключено, то согласно логу мы сразу проскакиваем во второй шаг паузы.

![принудительный переход в 1 шаг](https://user-images.githubusercontent.com/52205473/168236227-28eb5941-6b96-4dd5-962b-24f47dfa978f.PNG)
![естественный переход в 5й шаг](https://user-images.githubusercontent.com/52205473/168236248-847c23a5-af7a-4672-88ad-a03d2eeb35cf.PNG)

**Comment by idzm** [comment]
После возобновления включается шаг, который был активным на момент паузы операции.
Добавил тесты, проверяющие переход от выполнения к паузе и опять к выполнению. Всё работает корректно.

**Comment by AlexandraNovik** [comment]
Для наших проектов такое поведение может привести к поломке оборудования, так как в паузе мы переходим в исходное состояние. После чего в выполнении должны корректно из него выйти.
Нужна возможность или указать в самом объекте его поведение: переход из паузы в выполнение по умолчанию в шаг, в котором находились, или в шаг указанный в еплане или функции on_start. 
Или второй вариант: отдать приоритет функции on_start. Если в ней указан принудительный переход в шаг, то отправиться в него. Если функция пустая, то переход в шаг, который был до паузы.
Подскажите, мне это оформить отдельным запросом?

**Comment by idzm** [comment]
Да, это отдельным запросом.
