### ISSUE TITLE
Переход состояний операций

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa_main#428]
В проекте "S1-Сыворотка" возникла следующая ситуация:
На короткое время пропадает сигнал DO с состояния "Пауза" в состояние "Выполнение". Данный сигнал описан в операции в состояниях "Выполнение" и "Пауза". Однако при переходе с состояния "Пауза" в состояние "Выполнение" сигнал на короткое время (~30мс) пропадает и далее становится активным. 

**Сообщения из отладчика**
```
BEGIN "Танк 13 на вибросито Линия W2_OUT 3" (OBJECT9) set operation №2 ("Выдача") --> PAUSE.
    FINAL ACTIVE STEP №3
    "Шаг операции"
      Включать: { {W2DO1} }
      Выключать: { {W2_OUTDO64201 W2_OUTDO64211} }
END "Танк 13 на вибросито Линия W2_OUT 3" set operation № 2 --> PAUSE, res = 0.
state[ 0 ] = 2 (10)

tech_object::set_cmd() - prop = "CMD", val = 101301.000000
BEGIN "Мастер 1" (OBJECT1) set operation №13 ("Выдача из танков по линии W2_OUT") --> ON.
    "Шаг операции" 
END "Мастер 1" set operation №13 --> ON, res = 0.
state[ 0 ] = 8392704 (100000000001000000000000)
state[ 1 ] = 0 (0)

BEGIN "Танк 13 на вибросито Линия W2_OUT 3" (OBJECT9) set operation №2 ("Выдача") --> ON.
    "Шаг операции" 
      Включать: { {W2DO1} }
      Выключать: { {W2V23 W2V21 W2V22} }
    "Танк 13 на вибросито Линия W2_OUT" operation 2 "run" to_step() -> 3, step time 0 ms, next step -1.
    "Из танка 13"
      Включать: { {W2V13} }
END "Танк 13 на вибросито Линия W2_OUT 3" set operation № 2 --> ON, res = 0.

state[ 0 ] = 2 (10)

SOMETHING WRONG
```

**SOMETHING WRONG** использовал в качестве обнаружения проблемы: 
 ```
if oper_state == operation.RUN and not self.extra_signal[ 1 ].out:is_active() then
    print( "SOMETHING WRONG" )
end
```

**Comment by KUZMA-1989** [comment]
@idzm @AlexandrBehunkov  У меня тоже есть проблема с миганием сигналов между BR1-Приемка и BR1-Танки сыворотки и воды. Сигнал готовности мойки W25DO1 в BR1-Приемка прописан во время выполнения операции мойка в поле "Устройства" и он в BR1-Приемка не мигает. А уже в проекте BR1-Танки сыворотки и воды сигнал готовности мойки W25DI1 мигает и постоянно возникает краткосрочная ошибка объекта CIP на  МСА. Не знаю в чем причина, помогите разобраться. Уже докладную производство написало

**Comment by alexandraneroda** [comment]
Добрый день, 
1. Задержка при переходе из состояния Пауза в Выполнение. Почему тогда нет задержек при переходе в другие состояния?
2. Повторяется ли до сих пор данная проблема?
3. Может ли быть вероятность, что проблема не в коде?
4. Есть ли в коде какой-то пример, где подобная проблема была устранена? Я подразумеваю пример работы в подобных ситуациях

**Comment by AlexandrBehunkov** [comment]
@alexandraneroda Добрый день.
1. При переходе в состояние "Стоп" возможно только отключение операции
2. Проблему решили программно. Отправляем сигнал во время состояния "Пауза"( описано в main.plua ).
3. Не могу дать точный ответ.
4. Да, в данном же проетке [ Вот тут ] (https://github.com/savushkin-r-d/S1-Whey/commit/66bfdf13e0cd180f4ac76d0833172311d6c927ad)

**Comment by alexandraneroda** [comment]
Решено здесь - #448

**Comment by AlexandrBehunkov** [comment]
@alexandraneroda Включение шага по сигналу и переход состояний операций это две разные вещи. Или там внесены соответствующие правки?

**Comment by alexandraneroda** [comment]
@AlexandrBehunkov Вы правы. Я перепутала issue, извините.
