### ISSUE TITLE
Добавить промышленный  рефрактометр iPR FR2 

### ISSUE THREAD

**Issue by Serega-pixel** [savushkin-r-d/ptusa_main#434]
В связи с использованием рефрактометров iPR FR2 (SCHMIDT + HAENSCH GmbH & Co. iPR FR2)  на производстве (на линиях для измерения количества сухих веществ (BRIX)  в потоке), необходима реализация  устройства с управлением по аналоговому сигналу  4-20 mА. Линейная зависимость: датчик учитывает текущую температуру , выдаёт готовое значение, а мы его пересчитываем в %.
Следует реализовать следующее:
  - [ ] Измерение количества сухих веществ  в RI- показатель преломления (с точностью до пяти знаков после запятой),  делать пересчёт в %,Brix. Диапазон 0-50 % для протоколирования;
  -  [ ] Возможность изменения калибровочного числа.

**Comment by Serega-pixel** [comment]
[Технические характеристики рефрактометра.pdf](https://github.com/savushkin-r-d/ptusa_main/files/8832444/default.pdf)

**Comment by Serega-pixel** [comment]
@KUZMA-1989 @idzm @AndreyNemenkov  как данное устройство обозначать на функциональной схеме? Устройство как QT1, но такое устройство имеется

**Comment by KUZMA-1989** [comment]
> @KUZMA-1989 @idzm @AndreyNemenkov  как данное устройство обозначать на функциональной схеме? Устройство как QT1, но такое устройство имеется

QT2 обозначь. Но только пусть работают по типу изделия и определяет программа,что это рефрактометр

**Comment by idzm** [comment]
Возможность изменения температуры - @Serega-pixel, а по-подробнее, что имеется в виду?

**Comment by idzm** [comment]
Вот документация:
[Usermanual_iPR_FR2_ENG_v4.pdf](https://github.com/savushkin-r-d/ptusa_main/files/8832836/Usermanual_iPR_FR2_ENG_v4.pdf)

**Comment by idzm** [comment]
@Serega-pixel - что с данным устройством делаем? Хватает функциональности устройства **QT**?

**Comment by idzm** [comment]
Функциональности устройства QT достаточно для описания данного устройства.
