### ISSUE TITLE
Модернизация работы логики включения шага по сигналу

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/ptusa_main#445]
Добавить в шагах в eplaner в поле "Сигнал для включения шага" параметр "Выключать шаг по пропаданию сигнала" Да/Нет. Если "Нет", то шаг только включается, если "Да", то и включается и выключается по появлению и пропаданию данного сигнала.

**Comment by idzm** [comment]
Зависит от https://github.com/savushkin-r-d/ptusa-Lua-system/pull/13.
