### ISSUE TITLE
Возобновление опроса устройств IO-Link после аварии

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/ptusa_main#476]
Возникла ситуация, когда датчик текущего уровня был в аварии (значение в проекте 1000), датчик поменяли, авария в проекте осталась, но на модуле контроллера ошибки уже не было. Значение из датчика начало отображаться в проекте только после перезагрузки узла контроллера по питанию. Поправить опрос датчика после ошибки.

**Comment by idzm** [comment]
Выяснилось, что это происходит из-за того, что статусный бит не возвращается в активное состояние (остаётся в ошибке) после подключения устройства. Был задан соответствующий вопрос на форуме PLCnext - https://www.plcnext-community.net/forum/#/discussion/2915/axl-f-bk-eth-problems-with-reading-io-link-devices-status/p1?new=1.

**Comment by idzm** [comment]
Решено - необходимо обновлять прошивку модулей. В новой прошивке данной ошибки не наблюдается.
