### ISSUE TITLE
Изменение 555 операции мойки

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa_main#493]
Необходимо увеличить время операции **555** мойки (не успевают дойти сигналы до всех проектов при их обмене через `shared.lua`).

**Comment by idzm** [comment]
@AlexandrBehunkov - на сколько увеличить?

**Comment by AlexandrBehunkov** [comment]
@idzm до 6 секунд( на данный момент время составляет 3 секунды )

**Comment by idzm** [comment]
@AlexandrBehunkov - может это время реализовать в виде параметра с возможностью изменения?

**Comment by idzm** [comment]
Закрыто, так как возможно вопрос в реализации конкретных проектов и особенностей их взаимодействия.

**Comment by asutp-user** [comment]
![изображение](https://user-images.githubusercontent.com/60432181/205589199-05bc190a-cf17-447b-9571-aca6081be618.png)
Из ДЗ ВП №2726 от 10.11.2022.
Не выключается мойка линии ТР при появлении сигнала мойка завершена.
Разбирайтесь!
