### ISSUE TITLE
Обращение к весам Ethernet

### ISSUE THREAD

**Issue by AlexandraNovik** [savushkin-r-d/ptusa_main#589]
При попытке обращения к устройству **WT** (`WT_ETH`) из программы на **Lua** через  функции `get_state()`, `get_value()` программа аварийно завершается.

**Comment by AlexandraNovik** [comment]
Для весов отрабатывает получение значения, но функция get_state() выдает ошибку. Нужна проверка состояния устройства. Может быть ситуация, когда связь с ним потеряна.

**Comment by AlexandraNovik** [comment]
Функции обрабатываются get_state(), get_value() обрабатываются, программа не выдает ошибок. Из нюансов, наличие сетевого устройства WT_ETH увеличивает время цикла в 10 раз. В обычном случае время колеблется в районе 30 мсек 
![image](https://github.com/savushkin-r-d/ptusa_main/assets/52205473/95df97d7-1976-4ab9-a996-b85a85268a32)

**Comment by idzm** [comment]
> Функции обрабатываются get_state(), get_value() обрабатываются, программа не выдает ошибок. Из нюансов, наличие сетевого устройства WT_ETH увеличивает время цикла в 10 раз. В обычном случае время колеблется в районе 30 мс:
> 
> ![image](https://user-images.githubusercontent.com/52205473/240511678-95df97d7-1976-4ab9-a996-b85a85268a32.png)

Вопрос о быстродействии предлагаю оформить в новом **issue**.
