### ISSUE TITLE
Переход между состояниями операций

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#657]
Необходимо исправить переход между состояниями операций по структуре ( https://github.com/savushkin-r-d/EasyEPLANner/blob/master/docs/user_manual/images/transition_between_operations.svg ).
Если не прописаны промежуточные состояния операций ( становится в паузу, выходит из паузы, запуск, останавливается ) сразу переходим в основное состояние.
То есть при выполнении условия перехода с основного состояния в другое основное сначала проверяется есть ли между ними описанное промежуточное, если есть, идёт выполнение условий в шаге этого состояния, и далее по какому либо условию ( например так же по условию "переход к состоянию по условию" включаем основное состояние ( unpausing -> run or stop ), ( PAUSING -> PAUSE ) и т.п.
https://github.com/savushkin-r-d/BR1-Aseptic-Tank/pull/35#issuecomment-1934160593

**Comment by idzm** [comment]
> Из состояния **PAUSE** (с использованием "переход к состоянию по условию") в состояние **IDLE** и в состояние **STOP** не переходит, как и из состояния **RUN** в состояние **STOP**, учитывая и промежуточные состояния, когда они есть.

Из состояния **PAUSE** (с использованием "переход к состоянию по условию") в состояние **IDLE** `нет` и не может быть перехода - есть только: **PAUSE** или **RUN** --> (**STOPPING** - при наличии описания ) --> **STOP**.

**Comment by SergeiSilakov** [comment]
> > Из состояния **PAUSE** (с использованием "переход к состоянию по условию") в состояние **IDLE** и в состояние **STOP** не переходит, как и из состояния **RUN** в состояние **STOP**, учитывая и промежуточные состояния, когда они есть.
> 
> Из состояния **PAUSE** (с использованием "переход к состоянию по условию") в состояние **IDLE** `нет` и не может быть перехода - есть только: (**UNPAUSING** - при наличии описания), **PAUSE**, (**PAUSING - при наличии описания**) --> (**STOPPING** - при наличии описания) --> **STOP**; (**STARTING - при наличии описания**), **RUN** --> (**STOPPING** - при наличии описания) --> **STOP**.

@idzm согласен, (UNPAUSING - при наличии описания), PAUSE, (PAUSING - при наличии описания) --> (STOPPING - при наличии описания) --> STOP;
(STARTING - при наличии описания), RUN --> (STOPPING - при наличии описания) --> STOP. это без промежуточных состояний не работает, на сколько я помню когда изначально тестировал есть ли переходы то и с переходными состояниями не получилось.
