### ISSUE TITLE
Работа сигнальной колонны

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#666]
Для `G_SIREN_LIGHTS_MANAGER()` добавить возможность использовать сигнальную колонну с типом устройства **IO-Link**.

**Comment by SergeiSilakov** [comment]
Так же не корректно работают методы вызываемые из aggregate.lua для сигнальной колонны:
show_idle() не выключает красную сигнальную лампу( или другое состояние которое было включено в предыдущих циклах программы ) так же после вызова show_error_exists() в другие состояния колонна не переходит.

**Comment by SergeiSilakov** [comment]
При использовании сигнальной колонны с подключением DI работает корректно при вызове методов из aggregate.lua

**Comment by idzm** [comment]
> Так же не корректно работают методы вызываемые из aggregate.lua для сигнальной колонны: show_idle() не выключает красную сигнальную лампу( или другое состояние которое было включено в предыдущих циклах программы ) так же после вызова show_error_exists() в другие состояния колонна не переходит.

Это надо отдельным **issue** оформить.

**Comment by idzm** [comment]
> Для `G_SIREN_LIGHTS_MANAGER()` добавить возможность использовать сигнальную колонну с типом устройства **IO-Link**.

Данный функционал - `G_SIREN_LIGHTS_MANAGER()` - устарел, его не рекомендуется использовать. В будущих версиях его реализация будет удалена - необходимо использовать устройство **"сигнальная колонна"** и привязывать её к соответствующим аппаратам (`unit`) или агрегатам (`aggregate`).
