### ISSUE TITLE
Работа сигнальной колонны IOLink c привязкой

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#668]
- [x] При привязки сигнальной колонны **IO-Link** к объекту (например, к танку), она работает не корректно (тестировал на столе), при включении режима с жёлтой лампой или красной в состояние с зелёной не переходит, и при включении красной - жёлтый так же не включается. Это наблюдается только с **IO-Link**, с дискретными каналами такого нет. 
      Методы вызываемые из `aggregate.lua` для сигнальной колонны:
`show_idle()` не выключает красную сигнальную лампу (или другое состояние, которое было включено в предыдущих циклах программы), так же после вызова `show_error_exists()` в другие состояния колонна не переходит.
- [ ] При использовании одной колонны на весь проект необходимо будет её добавлять в каждый агрегат (аппарат), иначе например при какой либо аварии устройства или объекта колонна не будет сигнализировать об этом. Нужно добавить возможность привязать её ко всему проекту, если полностью уходить от `G_SIREN_LIGHTS_MANAGER()` - перемещено в https://github.com/savushkin-r-d/ptusa-Lua-dairy-system/issues/767.
- [ ] Так же в пользовательских объектах в данный момент нельзя использовать функционал для сигнальной колонны без дополнительного пользовательского описания. В некоторых случаях предлагаю использовать 2-й пункт для реализации колонны для всего проекта - перемещено в https://github.com/savushkin-r-d/ptusa-Lua-dairy-system/issues/767.

**Comment by SergeiSilakov** [comment]
Методы вызываемые из aggregate.lua для сигнальной колонны:
show_idle() не выключает красную сигнальную лампу (или другое состояние, которое было включено в предыдущих циклах программы), так же после вызова show_error_exists() в другие состояния колонна не переходит.

**Comment by SergeiSilakov** [comment]
@idzm То что описано в 1 таске не работает только в эмуляторе, прописано тут 
https://github.com/savushkin-r-d/ptusa_main/blob/ed3450372b7c2ca0025e10739f8cbf10dd3f9208/PAC/common/PAC_dev.cpp#L1019
Это не значительно, поэтому есть ли смысл это выносить в сборку для винды тут не уверен.

**Comment by idzm** [comment]
@SergeiSilakov - второй пункт надо переместить в https://github.com/savushkin-r-d/ptusa-Lua-dairy-system. Здесь есть главный объект (ячейка процесса - у нас сейчас он мастер называется). Он при наличии привязанной сирены будет реализовывать такую функциональность.

**Comment by idzm** [comment]
@SergeiSilakov - третий пункт также надо переместить в https://github.com/savushkin-r-d/ptusa-Lua-dairy-system.

**Comment by SergeiSilakov** [comment]
> @SergeiSilakov - второй пункт надо переместить в https://github.com/savushkin-r-d/ptusa-Lua-dairy-system. Здесь есть главный объект (ячейка процесса - у нас сейчас он мастер называется). Он при наличии привязанной сирены будет реализовывать такую функциональность.

Если объект работает без мастера в таком случае как? Например: линия перекачки, и узлы которые не использую мастера.

**Comment by idzm** [comment]
Здесь неявно связь есть - ячейка процесса содержит в себе все аппараты (**units**), агрегаты (**aggregates**), устройства (**control modules**). Просто мы её `мастером` назвали и в ней выделили операции, которые совместно используют несколько объектов.
