### ISSUE TITLE
Возможность для шага указывать максимальное время выполнения

### ISSUE THREAD

**Issue by idzm** [savushkin-r-d/ptusa_main#674]
Для ограничения времени выполнения шага предлагается добавить соответствующую функциональность (при описании шага необходимо будет указывать параметр - если требуется). При превышении данного времени будет выдаваться соответствующее сообщение и операция будет становиться на паузу. При возобновлении операции после данной аварии отсчёт данного времени опять начнётся с нуля заново.

**Comment by idzm** [comment]
@KUZMA-1989, @SergeiSilakov, @Serega-pixel - что скажете?

**Comment by AlexandrBehunkov** [comment]
@idzm Идея хорошая. Как смотрите на счет вот такой реализации:
1. Добавляем дополнительное поле к **Время шага** и **Номер следующего шага** - **Переход в паузу по завершению времени операции**. По умолчанию оно _False_. Дополнительное поле времени может путать пользователя.

**Comment by idzm** [comment]
Поля `Время шага` и `Номер следующего шага` - остаются как есть. Дополнительно появляется новое поле - `Максимальное время шага` - по его истечению операция становится на паузу. Если поле `Время шага` задано, то тогда поле `Максимальное время шага` не доступно (оно не имеет смысла).
