### ISSUE TITLE
Некорректная работа ошибки счета импульсов FQT 

### ISSUE THREAD

**Issue by KUZMA-1989** [savushkin-r-d/ptusa_main#677]
**Некорректно работает выход из ошибки**. Если сработала, ошибка по отсутствию счета импульсов, то операция становится в паузу и состояние FQT -10. После установления FQT состояния 1 и запуска выполнения, то ошибка должна проверится снова и должен сработать время параметра проверки P_DT. **А сейчас оно после перезапуска, не проверяет это время, а сразу выдает опять ошибку FQT -10 и ставит в паузу операцию**

**Comment by idzm** [comment]
Запуск операции не влияет на состояние счётчика - надо сбросить ошибку счётчика, далее опять проверяется условие корректной работы заданное время.

**Comment by idzm** [comment]
По появлению сообщения об ошибке счётчика - состояние `-10` - надо отдельное **issue** создать.
