### ISSUE TITLE
Некорректный вывод сообщения

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#687]
![what_is_it_1](https://github.com/savushkin-r-d/ptusa_main/assets/139815520/f9fb73e6-ca62-4e9f-9f0b-5e20016b9194)
При использовании максимального времени шага при его истечении выдаёт некорректное сообщение

**Comment by SergeiSilakov** [comment]
При выводе сообщения об ошибке счёта импульсов -10 и появлении счёта, в сообщении удаляется текст сообщения @
![Screenshot_1](https://github.com/savushkin-r-d/ptusa_main/assets/139815520/0179af3a-79a2-4d26-b088-dae635a80fd8)
![Screenshot_2](https://github.com/savushkin-r-d/ptusa_main/assets/139815520/55024a7d-2a48-4999-b1cb-ca6d3ba70101)

**Comment by SergeiSilakov** [comment]
Так же было бы неплохо добавить вывод информации о времени step_max_duration при дебаге
![image](https://github.com/savushkin-r-d/ptusa_main/assets/139815520/1b604362-e652-47e4-ab93-5622f5b00642)

**Comment by SergeiSilakov** [comment]
Версия программы от 28.03.2024

**Comment by idzm** [comment]
> При выводе сообщения об ошибке счёта импульсов -10 и появлении счёта при не подтверждённом сообщении, в сообщении удаляется текст сообщения ![Screenshot_1](https://private-user-images.githubusercontent.com/139815520/325486996-0179af3a-79a2-4d26-b088-dae635a80fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU0MjQsIm5iZiI6MTcxNDAzNTEyNCwicGF0aCI6Ii8xMzk4MTU1MjAvMzI1NDg2OTk2LTAxNzlhZjNhLTc5YTItNGQyNi1iMDg4LWRhZTYzNWE4MGZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTNiNzI1MjUxMmNhNWZiM2M4YTNjOWEyNjgxYjAzYTgwNjQzMzJkNjg1NGY5OGIxOTUyN2M2MDdkOTJlZGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mgMKy0JyQU3mMFvCFwWusm7e24d1Qb9kgSeRYNB8iHk) ![Screenshot_2](https://private-user-images.githubusercontent.com/139815520/325487007-55024a7d-2a48-4999-b1cb-ca6d3ba70101.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU0MjQsIm5iZiI6MTcxNDAzNTEyNCwicGF0aCI6Ii8xMzk4MTU1MjAvMzI1NDg3MDA3LTU1MDI0YTdkLTJhNDgtNDk5OS1iMWNiLWNhNmQzYmE3MDEwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDAyNzFiYTc3M2NkMzVkMjc1NjU1MTkyYTI5OTRiNzBhOTAyYjQ4OWVkMWE3NzAzODg2NzFiZDQ1ZmE4NDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QPbv6OFQYxdLFEVilf60jy0U4YKZt2gaJvakRqEe1xU)

Это надо оформить отдельным запросом (issue).

**Comment by idzm** [comment]
> Так же было бы неплохо добавить вывод информации о времени step_max_duration при дебаге ![image](https://private-user-images.githubusercontent.com/139815520/325491079-1b604362-e652-47e4-ab93-5622f5b00642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU0MjQsIm5iZiI6MTcxNDAzNTEyNCwicGF0aCI6Ii8xMzk4MTU1MjAvMzI1NDkxMDc5LTFiNjA0MzYyLWU2NTItNDdlNC1hYjkzLTU2MjJmNWIwMDY0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwODUyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjUwNWVkN2ZkOWNkMTU1OWM1MGFjN2ZmOWFhNzFmNGQ4ZmFlNjhkZWFhNjliMzUxMmRhMGViNTQ2YWVmOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.49nYYSuMRGgoiwe0z3mjIRgALvQHR9cymPMYhdmr-5Y)

Это надо оформить отдельным запросом (issue).
