### ISSUE TITLE
Доработка ошибки расходомера 

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#695]
Если привязать насос к расходомеру, при включённом насосе, если прошло время запуска насоса и нет расхода, то после отсчёта времени расходомера `P_DT`, если не появился поток, должна появится ошибка **"Нет потока"**.

**Comment by idzm** [comment]
> Если привязать насос к расходомеру, при включённом насосе, если прошло время запуска насоса и нет расхода, то после отсчёта времени расходомера `P_DT`, если не появился поток, должна появится ошибка **"Нет потока"**.

@SergeiSilakov - "прошло время запуска насоса" - это какой параметр?

**Comment by SergeiSilakov** [comment]
@idzm P_ON_TIME я этот параметр имел ввиду

**Comment by idzm** [comment]
@SergeiSilakov - возник вопрос. Расходомер - сложное электронно-механическое устройство, какова вероятность, что он будет считать импульсы (расход, м3), но при этом поток будет показывать 0 (л/мин)?

**Comment by KUZMA-1989** [comment]
> @SergeiSilakov - возник вопрос. Расходомер - сложное электронно-механическое устройство, какова вероятность, что он будет считать импульсы (расход, м3), но при этом поток будет показывать 0 (л/мин)?
> @KUZMA-1989 - что скажешь?

Вероятность есть всегда

**Comment by KUZMA-1989** [comment]
> Если привязать насос к расходомеру, при включённом насосе, если прошло время запуска насоса и нет расхода, то после отсчёта времени расходомера `P_DT`, если не появился поток, должна появится ошибка **"Нет потока"**.

@idzm @SergeiSilakov это же раньше работало. Возникала ошибка текстовая, а если счётчик привязан к полю проверяемые устройства, то линия становилась в паузу.

**Comment by SergeiSilakov** [comment]
@idzm условие при котором вылетает ошибка по счётчику связана с расходом, не появится ошибка по потоку если расход будет ниже минимального( ну или в этом случае вообще не будет ), поэтому смысл больше в индикации( предупреждении ) о возможной не корректной работе.

**Comment by SergeiSilakov** [comment]
Единственный момент, что если насос работает с нулевым заданием, в этом случае вылетит ошибка по расходу хоть насос и не качал в случае когда минимальное задание в параметрах частотника не ограничено нижней границей.

**Comment by KUZMA-1989** [comment]
> Единственный момент, что если насос работает с нулевым заданием, в этом случае вылетит ошибка по расходу хоть насос и не качал в случае когда минимальное задание в параметрах частотника не ограничено нижней границей.

Параметр P_ERR_MIN_FLOW для этого и сделан, чтоб исключить погрешность и нулевую частоту на насосе

**Comment by idzm** [comment]
Так когда здесь делаем? Если задана нулевая частота на насосе, то расход не появится. Проверять насос не только на включение, но и на ненулевую частоту (>0)?

**Comment by KUZMA-1989** [comment]
> Так как здесь делаем? Если задана нулевая частота на насосе, то расход не появится. Проверять насос не только на включение, но и на ненулевую частоту (>0)?

**Не надо**, я ж говорю, что Параметр P_ERR_MIN_FLOW ставишь 1, тогда расход меньше 1 обрабатываться не будет. Они могут поставить задание частоты нижнее на самом частотнике 10 Гц например, тогда при 0 задании будет расход идти, а ошибка не возникнет

**Comment by KUZMA-1989** [comment]
@idzm @SergeiSilakov Не актуальный запрос. Ошибка уже реализована в действующем функционале. Расход есть, должны быть импульсы. 
Может быть для расходомера типа "FQT", там где нет импульсов данный функционал актуален будет? @idzm Что скажешь?

**Comment by idzm** [comment]
У нас нет счётчика без импульсов - есть только счётчик без расхода.

**Comment by KUZMA-1989** [comment]
Тогда закрываем
