### ISSUE TITLE
Автоматический учёт суточного расхода потребителей 

### ISSUE THREAD

**Issue by Serega-pixel** [savushkin-r-d/ptusa_main#704]
Разработать логику в стандартном счетчике в **ptusa_main** для дополнительного поля, чтоб туда суммировалось значение за сутки, а потом в конце суток сбрасывалось. Для  универсальности функционала мойку не учитывать, а суммировать только в операциях производства, использовав логический счётчик, который, например, привязан к линии.

**Comment by idzm** [comment]
https://github.com/savushkin-r-d/S1-Concentrated-solutions/issues/9
