### ISSUE TITLE
Проверка команд для управления ручным режимом устройств

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa_main#722]
Для всех устройств необходимо добавить функцию проверки активности ручного режима: в устройствах если в поле ручного режима записывается значение >1, то возвращать 0. Активность ручного режима должна выполняться только отправкой значения 0/1.

**Comment by idzm** [comment]
@AlexandrBehunkov - тут нужны пояснения: что эта функция должна делать и как она будет использоваться.

**Comment by AlexandrBehunkov** [comment]
@idzm Эта функция нужна для проверки любого устройства на ручной режим. В последующем планируется создать "индикатор", который будет указывать на активность ручного режима в группе сигналов/устройств.

**Comment by idzm** [comment]
А зачем нам такой индикатор?

**Comment by AlexandrBehunkov** [comment]
Были ситуации, когда сигнал DO/AO переводили в ручной режим и при трансляции на данный сигнал значения, оно не передавалось.

**Comment by idzm** [comment]
Все правильно - если устройство в ручном режиме, то оно управляется оператором, а все остальное игнорируется. Или нужна какая-то другая логика?

**Comment by AlexandrBehunkov** [comment]
Нет, логику менять не нужно. Нужно подумать над визуализацией активности ручного режима для AO сигналов. Для этого я и планировал создать пользовательскую функцию в lua, для обработки устройств, ручной режим которых не отображается.

**Comment by idzm** [comment]
Так есть тег is_manual - по нему можно определить, активен ли ручной режим.

**Comment by AlexandrBehunkov** [comment]
Вопрос: как понять, что в сигнале AO включен ручной режим?

**Comment by idzm** [comment]
Тег `M` - по нему можно определить, активен ли ручной режим: **1** - ручной режим активен, **0** - ручной режим неактивен.
