### ISSUE TITLE
Добавить новое устройство IO-Link - клапан GEA

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#728]
Тип устройства управления и подтипы: `DT_V` и `V_IOLINK_MIXPROOF`, `V_IOLINK_DO1_DI2` соответственно. 
Описание IO-Link клапана находится тут: https://ioddfinder.io-link.com/productvariants/search/21825
В текстовом виде из мануала: 
[IO_link Description.pdf](https://github.com/user-attachments/files/16660802/IO_link.Description.pdf)
Manual: 
[Control Top GEA T.VIS A-15.pdf](https://github.com/user-attachments/files/16661046/Control.Top.GEA.T.VIS.A-15.pdf)

![image](https://github.com/user-attachments/assets/cd30a858-877d-47cb-8024-66e234ca3ccc)

**Comment by idzm** [comment]
@SergeiSilakov - а откуда такая картинка?

**Comment by SergeiSilakov** [comment]
@idzm moneo

**Comment by SergeiSilakov** [comment]
[TA15.pdf](https://github.com/user-attachments/files/16760470/TA15.pdf)
Для клапанов типа Single-seat valves и Double-seat valves биты обратных связей различны, в данном мануале это указано.

**Comment by idzm** [comment]
Для образца можно использовать данный запрос - https://github.com/savushkin-r-d/ptusa_main/pull/167.

**Comment by Lenonim** [comment]
Артикул устройства GEA.T15P8IAJ

**Comment by SergeiSilakov** [comment]
> Артикул устройства GEA.T15P8IAJ

GEA.T**A**15P8IAJ

**Comment by SergeiSilakov** [comment]
И GEA.TA15L8IAJ для 3-х соленоидов

**Comment by idzm** [comment]
@painterlv - а у тебя в проекте какой артикул сейчас?

**Comment by painterlv** [comment]
Как говорит Сергей, так и есть в Eplan
