### ISSUE TITLE
Некорректная работа включения/отключения устройств с задержкой при переходе между шагами

### ISSUE THREAD

**Issue by SergeiSilakov** [savushkin-r-d/ptusa_main#733]
При переходе из шага где было отключено устройство **X** в шаг, где прописано выключать устройство **Х** с задержкой, устройство **Х** включается и выключается через время заданное параметром.

Как должно быть:
При переходе в шаг в котором прописано включать с задержкой необходимо проверять было ли устройство включено: 
1. если включено значит оставляем включённым;
2. если отключено значит включаем через время указанное в параметре( данный пункт работает );

При переходе в шаг в котором прописано выключать с задержкой необходимо проверять было ли устройство выключено: 
1. если отключено значит оставляем отключённым;
2. если включено значит выключаем через время указанное в параметре( данный пункт работает );

Пример:
При наполнении танков при переключении между танками( переход шагов ), возникает проблема если прописать в задержку включения/выключения клапана, при переходе отключаются/включаются клапана когда они уже были включены/выключены.

**Comment by idzm** [comment]
Шаги работают независимо друг от друга, единообразно вне зависимости от того, в какой последовательности они выполняются. Это специально так сделано, чтобы не было запутанности. Если необходимо что-то по-другому делать с каким-то отдельным устройством, выделяем его в отдельный шаг, который выполняется параллельно - тогда таких проблем не будет.

**Comment by idzm** [comment]
Данная проблема решается с помощью переходного совместного выполнения шагов - https://github.com/savushkin-r-d/ptusa_main/pull/777.
