### ISSUE TITLE
Новый тип датчика IFM PM1706

### ISSUE THREAD

**Issue by painterlv** [savushkin-r-d/ptusa_main#795]

**Comment by idzm** [comment]
[Вот](https://www.ifm.com/download/files/ifm-000299-20240604-IODD11-en/$file/ifm-000299-20240604-IODD11-en.pdf) документация (взята [отсюда](https://www.ifm.com/us/en/product/PM1706#documents)):
[ifm-000299-20240604-IODD11-en.pdf](https://github.com/user-attachments/files/17868149/ifm-000299-20240604-IODD11-en.pdf)

**Comment by idzm** [comment]
Связано с https://github.com/savushkin-r-d/EasyEPLANner/issues/1459.
