### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by AlexandrBehunkov** [savushkin-r-d/ptusa_main#815]
При запуске проекта контроллер выдавал следующие сообщения: Too many open files.

![image](https://github.com/user-attachments/assets/33a8b9ba-2bdf-4701-83ee-bf29395cbb2d)

**Comment by idzm** [comment]
Описание решения проблемы тут - https://winitpro.ru/index.php/2019/11/19/oshibka-too-many-open-files-v-linux/.

Максимально количество файловых дескрипторов, которые могут быть открыты в вашей файловой системе всеми процессами можно узнать так:
```sh
# cat /proc/sys/fs/file-max
```
Чтобы узнать, сколько файлов открыто сейчас:
```sh
$ cat /proc/sys/fs/file-nr 
```

Выведем ограничение на количество открытых файлов для одного процесса текущего пользователя:
```sh
# ulimit -n
```
По умолчанию количество файлов для одного процесса этого ограничено числом 1024.

Выведем максимальное количество для одного пользователя (max user processes):
```sh
# ulimit –u
```

Количество открытых файлов для процесс PID=6923:
```sh
 ls -l /proc/6923/fd | wc -l
```


Открытые файлы для процесса PID=6923:
```sh
 ls -l /proc/6923/fd
```
